CC=cc

FLAGS=-O3

all: life

life: life.c
	$(CC) -fopenmp $(FLAGS) life.c -o life

clean:
	rm -f life

# CC=cc

# FLAGS=-O3

# all: life

# life: life.go
# 	go build -o life life.go 

# clean:
# 	rm -f life
# 	go clean
